Add final name "Crime-Database"
Patlenlix/CrimeDatabase pull request #59
Opened 2022-03-14 15:50 UTC by FelixJacobsen

Fix #51 

Adding final name in pom.xml

2022-03-14 16:03 UTC, HelenaHalldinITHS commented
When adding the final name, maybe we should update the dockerfile as well? (So it works :) )

2022-03-14 17:04 UTC, LordRekishi commented
Do we need a final name? And is there another way to implement it in Spring Boot? I get the feeling this is not the right way? OR did we talk about this during class?

2022-03-14 17:26 UTC, FelixJacobsen commented
Finalname has nothing to do with Spring boot I think, it's more to have a static name for deployment/tests? 

![image](https://user-images.githubusercontent.com/89127725/158227070-0e62c742-8bad-4864-bfc6-967a623bf551.png)

2022-03-14 18:02 UTC, LordRekishi commented
> Finalname has nothing to do with Spring boot I think, it's more to have a static name for deployment/tests?
> 
> ![image](https://user-images.githubusercontent.com/89127725/158227070-0e62c742-8bad-4864-bfc6-967a623bf551.png)

Should it be scrapped then? Do we get any benefit from it?

2022-03-16 06:48 UTC, HelenaHalldinITHS commented
The docker file uses "CrimeDatabase-0.0.1-SNAPSHOT.jar ", which we will have to change during the lifetime of the application (When we make a release we will remove SNAPSHOT and then increase the number). If we have a final name we don't have to remember to update the dockerfil each time we update the version of the project :)

2022-03-18 11:15 UTC, LordRekishi requested changes

2022-03-18 11:15 UTC, LordRekishi commented on pom.xml
> +        <finalName>Crime-Database</finalName>
```suggestion
        <finalName>crime-database</finalName>
```

2022-03-18 11:28 UTC, LordRekishi approved these changes

2022-03-18 11:28 UTC, merged