Add unit tests for CategoryService
Patlenlix/CrimeDatabase pull request #81
Opened 2022-03-22 09:46 UTC by HelenaHalldinITHS

This will fix #80

2022-03-22 09:54 UTC, helenahalldiniths commented
**Some info:**
- This is more of a draft
- I have commented quite a lot since i'm bad at naming test-methods, feel free to propose other names.
- Since the class mostly is responsible for forwarding requests to the repository the tests feel quite simple, I'm wondering if there is something else that should be tested...?

**Some thoughts I got when working with theses tests (about the rest of the code):**
- The "error handling" of the update method should be moved to the service class.
- The delete method looks quite weird... first we send in the id, then we look for a catogory with said id, then we extract the id from said category and sends it to the "deleteById" method of the repository. Maybe insted we could just call the "deleteById" method and catch the error it throws if the id isn't valid and then throw our costume made exception?

2022-03-24 13:41 UTC, LordRekishi commented
Will take a look at this once I've gotten a bit further with JMS

2022-03-24 21:02 UTC, LordRekishi requested changes, later dismissed
Looks really nice otherwise, and full coverage! Nice!

2022-03-24 21:02 UTC, LordRekishi commented on src/test/java/se/iths/crimedatabase/service/CategoryServiceTest.java
> +    // said category should be passes to the save method of the repository
The comments are helpful for reviewing, but I believe we should remove them for the final merge?
Well named test methods are enough, or we could use `@DisplayName("Name here")`

2022-03-24 21:02 UTC, LordRekishi commented on src/test/java/se/iths/crimedatabase/service/CategoryServiceTest.java
> +                new Category().setName("shoplifting").setId(3L));
```suggestion
                new Category().setName("Shoplifting").setId(3L));
```
Let's change to a capital 'S' to correspond with the other categories and look better

2022-03-24 21:02 UTC, LordRekishi commented on src/test/java/se/iths/crimedatabase/service/CategoryServiceTest.java
> +    }
Should we perhaps make this into two separate test methods?

2022-03-24 21:02 UTC, LordRekishi commented on src/test/java/se/iths/crimedatabase/service/CategoryServiceTest.java
> +    }
Same here? Two methods instead?

2022-03-29 06:48 UTC, HelenaHalldinITHS commented
I have updated the branch and made some small canges.

2022-04-01 09:06 UTC, LordRekishi commented
I think we should try to use merge more than rebase. Merge main into our branch before pushing. That will solve all these commits doubling up.

2022-04-03 11:52 UTC, merged